
mybatis:
  type-aliases-package: com.yorkehan.pojo
logging:
  file: D:\software\java\idea-IU-182.5107.16\zk.log
  level:
    com.yorkehan: debug
pagehelper:
  helper-dialect: mysql

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
shiro:
  unauthorizedUrl: /403
  loginUrl: /login
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    druid:
